---

 - name: Update apt package cache
   apt:
     update_cache: yes

 - name: Install default-jdk
   apt:
     name: default-jdk
     state: present

 - name: Add group "tomcat"
   group:
    name: tomcat

 - name: Add user "tomcat"
   user:
    name: tomcat
    group: tomcat
    home: /usr/share/apache-tomcat

 - name: Download Tomcat archive
   get_url:
    url:  "https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.88/bin/apache-tomcat-9.0.88.tar.gz"
    dest: /opt
    mode: '0755'

 - name: Create tomcat directory with default permissions
   file:
    path: /opt/tomcat
    state: directory

 - name: Extract Apache Tomcat
   command: tar xzvf /opt/apache-tomcat-9.0.88.tar.gz -C /opt/tomcat --strip-components=1
   args:
     creates: /opt/tomcat/bin/startup.sh

 - name: Change ownership of Tomcat directories
   file:
     path: "{{ item }}"
     owner: tomcat
     group: tomcat
     state: directory
   with_items:
     - /opt/tomcat/webapps
     - /opt/tomcat/work
     - /opt/tomcat/temp
     - /opt/tomcat/logs

 - name: Add Tomcat systemd service
   copy:
     content: |
       [Unit]
       Description=Apache Tomcat Web Application Container
       After=network.target

       [Service]
       Type=forking
       Environment=JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre
       Environment=CATALINA_PID=/opt/tomcat/temp/tomcat.pid
       Environment=CATALINA_HOME=/opt/tomcat
       Environment=CATALINA_BASE=/opt/tomcat
       Environment='CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC'
       Environment='JAVA_OPTS=-Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom'
       ExecStart=/opt/tomcat/bin/startup.sh
       ExecStop=/opt/tomcat/bin/shutdown.sh
       User=tomcat
       Group=tomcat
       UMask=0007
       RestartSec=10
       Restart=always

       [Install]
       WantedBy=multi-user.target
     dest: /etc/systemd/system/tomcat.service
   notify: reload systemd

 - name: Start Tomcat service with systemd
   systemd:
     name: tomcat.service
     state: started
     enabled: yes  
